-- Run this file first from SYSTEM user

DROP USER ers CASCADE;

CREATE USER ers
IDENTIFIED BY baconandeggs
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA 10M ON users;

GRANT CONNECT TO ers;
GRANT RESOURCE TO ers;
GRANT CREATE SESSION TO ers;
GRANT CREATE TABLE TO ers;
GRANT CREATE VIEW TO ers;

--GRANT EXECUTE ON SYS.DBMS_CRYPTO TO ers;

conn ers/baconandeggs